version: "3"
services:
  web:
    build: './docker/php'
    ports:
      - '8000:8000'
    volumes:
      - './:/app'
      - './docker/php/zzz-xdebug.ini:/usr/local/etc/php/conf.d/zzz-xdebug.ini'
    working_dir: '/app'
    user: 'eugene'
    environment:
      XDEBUG_CONFIG: 'discover_client_host=true client_host=192.168.48.1 log_level=0'
    command:
      - 'php -S 0.0.0.0:8000 -t /app/publ'
